version: '3'
services:
  db:
    image:  postgres:latest
    # restart: always
    ports: 
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: ctincidendiasdb
    volumes:
      - ../postgres:/var/lib/postgresql/data